import { Drug } from '../types/drug';

export const drugs: Drug[] = [
  {
    id: 'epinephrine',
    name: 'Epinephrine',
    genericName: 'Adrenaline',
    category: 'Cardiac',
    class: 'Sympathomimetic',
    indications: ['Cardiac arrest (PEA, VF, pulseless VT, asystole)', 'Anaphylaxis', 'Severe asthma/bronchospasm', 'Symptomatic bradycardia refractory to atropine'],
    contraindications: ['No absolute contraindications in cardiac arrest', 'Relative: uncontrolled hypertension, tachydysrhythmias (non-arrest)'],
    sideEffects: ['Tachycardia', 'Hypertension', 'Angina', 'Anxiety', 'Tremor', 'Ventricular dysrhythmias'],
    adultDose: 'Cardiac arrest: 1 mg IV/IO q3-5 min | Anaphylaxis: 0.3-0.5 mg (1:1000) IM lateral thigh | Infusion: 2-10 mcg/min',
    pedsDose: 'Cardiac arrest: 0.01 mg/kg IV/IO (max 1 mg) q3-5 min | Anaphylaxis: 0.01 mg/kg IM (1:1000, max 0.5 mg)',
    routes: ['IV', 'IO', 'IM', 'ET (2-2.5x IV dose)'],
    onset: 'IV: 1-2 min | IM: 5-10 min',
    duration: '5-10 min',
    notes: 'Auto-injector (EpiPen) 0.3 mg adult, 0.15 mg peds. For cardiac arrest, give every other cycle of CPR.',
    scope: 'Both',
  },
  {
    id: 'amiodarone',
    name: 'Amiodarone',
    category: 'Cardiac',
    class: 'Class III Antidysrhythmic',
    indications: ['VF/pulseless VT (after defibrillation + epi)', 'Stable wide-complex tachycardia', 'SVT refractory to adenosine', 'Atrial fibrillation with RVR'],
    contraindications: ['Sinus bradycardia', 'AV block (without pacemaker)', 'Cardiogenic shock', 'Known hypersensitivity'],
    sideEffects: ['Hypotension', 'Bradycardia', 'Prolonged QT', 'Pulmonary toxicity (chronic)', 'Phlebitis at IV site'],
    adultDose: 'Cardiac arrest: 300 mg IV/IO push; 2nd dose 150 mg IV/IO | Stable VT: 150 mg IV over 10 min',
    pedsDose: 'Cardiac arrest: 5 mg/kg IV/IO (max 300 mg) | Stable: 5 mg/kg IV over 20-60 min',
    routes: ['IV', 'IO'],
    onset: '1-2 min',
    duration: '40 days (half-life)',
    notes: 'Dilute stable dose in D5W. Can cause blue skin discoloration with chronic use. Preferred over lidocaine in cardiac arrest.',
    scope: 'Paramedic',
  },
  {
    id: 'adenosine',
    name: 'Adenosine',
    category: 'Cardiac',
    class: 'Endogenous Nucleoside / AV Node Blocker',
    indications: ['SVT (PSVT) — narrow complex', 'Stable regular narrow-complex tachycardia'],
    contraindications: ['2nd/3rd degree AV block (without pacemaker)', 'Sick sinus syndrome', 'WPW with atrial fibrillation', 'Asthma/COPD (relative)'],
    sideEffects: ['Transient asystole', 'Flushing', 'Chest pressure', 'Dyspnea', 'Bronchospasm', 'Headache'],
    adultDose: '6 mg rapid IV push; if no response in 1-2 min → 12 mg; may repeat 12 mg once',
    pedsDose: '0.1 mg/kg rapid IV push (max 6 mg); 2nd dose 0.2 mg/kg (max 12 mg)',
    routes: ['IV (rapid push + flush)', 'IO'],
    onset: '15-30 sec',
    duration: '10-30 sec',
    notes: 'Must be given as rapid IV push followed immediately by 20 mL NS flush. Warn patient about chest pressure and brief asystole. Move IV as proximal as possible.',
    scope: 'Paramedic',
  },
  {
    id: 'aspirin',
    name: 'Aspirin',
    genericName: 'Acetylsalicylic Acid (ASA)',
    category: 'Cardiac',
    class: 'Antiplatelet / NSAID',
    indications: ['Suspected ACS/STEMI (chest pain of cardiac origin)', 'Ischemic stroke prevention'],
    contraindications: ['Active GI bleeding', 'Known allergy to aspirin or NSAIDs', 'Hemorrhagic stroke', 'Age < 16 (Reye syndrome risk)'],
    sideEffects: ['GI upset', 'GI bleeding', 'Tinnitus (overdose)', 'Bronchospasm in aspirin-sensitive patients'],
    adultDose: '324 mg (four 81mg chewable) PO — chewed, not swallowed whole',
    pedsDose: 'Not routinely given by EMS to pediatric patients',
    routes: ['PO (chewable)'],
    onset: '20-30 min',
    duration: '7-10 days (platelet effect)',
    notes: 'Give as early as possible in suspected ACS. Ensure patient can swallow/chew. Confirm no allergy before administering.',
    scope: 'Both',
  },
  {
    id: 'nitroglycerin',
    name: 'Nitroglycerin',
    genericName: 'NTG / Nitro',
    category: 'Cardiac',
    class: 'Nitrate / Vasodilator',
    indications: ['Chest pain/ACS (systolic BP > 100)', 'Acute pulmonary edema', 'Hypertensive emergency with chest pain'],
    contraindications: ['Systolic BP < 100 mmHg', 'Right ventricular infarct (inferior STEMI)', 'PDE-5 inhibitor use within 24-48h (Viagra, Cialis)', 'Severe aortic stenosis', 'Increased ICP'],
    sideEffects: ['Hypotension', 'Headache', 'Reflex tachycardia', 'Syncope', 'Flushing'],
    adultDose: '0.4 mg SL q5 min (max 3 doses); reassess BP before each dose',
    pedsDose: 'Not routinely used in peds EMS',
    routes: ['SL (sublingual)', 'Spray', 'Transdermal patch (remove before cardioversion)'],
    onset: '1-3 min (SL)',
    duration: '20-30 min',
    notes: 'ALWAYS check systolic BP before each dose. Verify no PDE-5 inhibitor use. Hold if SBP < 100 or drops > 20 mmHg.',
    scope: 'Both',
  },
  {
    id: 'fentanyl',
    name: 'Fentanyl',
    category: 'Pain/Sedation',
    class: 'Synthetic Opioid Agonist',
    indications: ['Moderate to severe pain', 'Procedural sedation adjunct', 'Trauma pain management', 'Burns'],
    contraindications: ['Respiratory depression', 'Hemodynamic instability (relative)', 'Known hypersensitivity'],
    sideEffects: ['Respiratory depression', 'Hypotension', 'Bradycardia', 'Nausea', 'Chest wall rigidity (high doses)'],
    adultDose: '1-2 mcg/kg IV/IO/IM slow push; intranasal 2 mcg/kg (max 4 mcg/kg total); titrate to pain relief',
    pedsDose: '1-2 mcg/kg IV/IO slow push; 2 mcg/kg intranasal (max 100 mcg)',
    routes: ['IV', 'IO', 'IM', 'IN (intranasal via MAD device)'],
    onset: 'IV: 1-2 min | IN: 5-10 min',
    duration: '30-60 min',
    notes: 'Preferred analgesic for trauma. Have naloxone available. Monitor SpO2 and respiratory rate continuously.',
    scope: 'Paramedic',
  },
  {
    id: 'morphine',
    name: 'Morphine Sulfate',
    category: 'Pain/Sedation',
    class: 'Opioid Agonist',
    indications: ['Moderate to severe pain', 'Acute pulmonary edema (adjunct)', 'ACS pain management'],
    contraindications: ['Respiratory depression', 'Head injury with altered LOC', 'Hypotension', 'Acute asthma'],
    sideEffects: ['Respiratory depression', 'Hypotension', 'Nausea/vomiting', 'Histamine release', 'Constipation'],
    adultDose: '2-4 mg IV slow push q5 min PRN; max 10-20 mg titrated | 5-10 mg IM',
    pedsDose: '0.1 mg/kg IV/IM (max 5 mg per dose)',
    routes: ['IV', 'IM', 'IO'],
    onset: 'IV: 5 min | IM: 15-30 min',
    duration: '3-5 hours',
    notes: 'Slower onset than fentanyl. Can cause significant hypotension. Use cautiously in inferior MI. Naloxone reversal available.',
    scope: 'Paramedic',
  },
  {
    id: 'naloxone',
    name: 'Naloxone',
    genericName: 'Narcan',
    category: 'Toxicology',
    class: 'Opioid Antagonist',
    indications: ['Opioid overdose (respiratory depression, unresponsiveness)', 'Suspected narcotic toxidrome'],
    contraindications: ['Known hypersensitivity (rare)'],
    sideEffects: ['Acute opioid withdrawal (agitation, vomiting, pulmonary edema)', 'Tachycardia', 'Hypertension'],
    adultDose: '0.4-2 mg IV/IM/IO/IN; titrate to adequate respirations (not full reversal in dependent patients); may repeat q2-3 min',
    pedsDose: '0.01 mg/kg IV/IO (max 0.4 mg); 0.1 mg/kg IM if < 5 years',
    routes: ['IV', 'IO', 'IM', 'IN (intranasal 4 mg/0.1 mL formulation)'],
    onset: 'IV: 2 min | IM/IN: 5-10 min',
    duration: '30-90 min (shorter than most opioids — redosing likely needed)',
    notes: 'Duration shorter than most opioids — patient may re-narcotize. Goal is adequate breathing, NOT full reversal. Narcan nasal spray: 4 mg IN. Monitor 1-2 hours minimum.',
    scope: 'Both',
  },
  {
    id: 'midazolam',
    name: 'Midazolam',
    genericName: 'Versed',
    category: 'Seizure/Neuro',
    class: 'Benzodiazepine',
    indications: ['Seizure management', 'Procedural sedation (RSI pre-medication)', 'Acute agitation', 'Anxiety'],
    contraindications: ['Respiratory depression', 'Shock', 'Known hypersensitivity to benzodiazepines', 'Acute angle-closure glaucoma'],
    sideEffects: ['Respiratory depression', 'Apnea (IV)', 'Hypotension', 'Anterograde amnesia', 'Paradoxical agitation'],
    adultDose: 'Seizure: 5-10 mg IM or 5 mg IN | Sedation: 2.5-5 mg IV slow (titrate) | Agitation: 5 mg IM/IN',
    pedsDose: 'Seizure: 0.2 mg/kg IM/IN (max 10 mg) | Sedation: 0.05-0.1 mg/kg IV',
    routes: ['IV', 'IO', 'IM', 'IN (intranasal)', 'Buccal'],
    onset: 'IV: 2-3 min | IM: 5-15 min | IN: 5-10 min',
    duration: '45-60 min',
    notes: 'Preferred EMS benzodiazepine. Preferred route for status epilepticus is IM if no IV access. Have BVM ready. Flumazenil is reversal agent.',
    scope: 'Paramedic',
  },
  {
    id: 'lorazepam',
    name: 'Lorazepam',
    genericName: 'Ativan',
    category: 'Seizure/Neuro',
    class: 'Benzodiazepine',
    indications: ['Seizures / status epilepticus', 'Acute anxiety', 'Alcohol withdrawal'],
    contraindications: ['Respiratory depression', 'Shock', 'CNS depression'],
    sideEffects: ['Respiratory depression', 'Sedation', 'Hypotension', 'Amnesia'],
    adultDose: '1-2 mg IV/IM; may repeat in 5 min (max 4 mg)',
    pedsDose: '0.05-0.1 mg/kg IV/IM (max 4 mg)',
    routes: ['IV', 'IM', 'IO'],
    onset: 'IV: 1-5 min | IM: 15-30 min',
    duration: '6-8 hours',
    notes: 'Longer duration than midazolam. Requires refrigeration.',
    scope: 'Paramedic',
  },
  {
    id: 'albuterol',
    name: 'Albuterol',
    genericName: 'Salbutamol / ProAir / Ventolin',
    category: 'Airway/RSI',
    class: 'Beta-2 Agonist / Bronchodilator',
    indications: ['Asthma', 'COPD exacerbation', 'Bronchospasm', 'Anaphylaxis (bronchospasm component)', 'Hyperkalemia (adjunct)'],
    contraindications: ['Hypersensitivity', 'Tachydysrhythmias (relative)'],
    sideEffects: ['Tachycardia', 'Tremor', 'Anxiety', 'Hypokalemia', 'Palpitations', 'Paradoxical bronchospasm'],
    adultDose: '2.5 mg in 3 mL NS via SVN nebulizer; may repeat q20 min (up to 3 doses) | MDI: 4-8 puffs',
    pedsDose: '2.5 mg nebulized (<20 kg: 1.25 mg) q20 min; MDI: 4-8 puffs with spacer',
    routes: ['Inhaled (SVN)', 'MDI', 'IV (hospital only)'],
    onset: '5-15 min',
    duration: '3-6 hours',
    notes: 'First-line for bronchospasm. May combine with ipratropium for severe exacerbations. Monitor HR during therapy.',
    scope: 'Both',
  },
  {
    id: 'ipratropium',
    name: 'Ipratropium Bromide',
    genericName: 'Atrovent',
    category: 'Airway/RSI',
    class: 'Anticholinergic / Bronchodilator',
    indications: ['Severe asthma (adjunct to albuterol)', 'COPD exacerbation'],
    contraindications: ['Hypersensitivity to atropine or ipratropium', 'Narrow-angle glaucoma (relative)'],
    sideEffects: ['Dry mouth', 'Blurred vision', 'Tachycardia', 'Urinary retention'],
    adultDose: '0.5 mg in 2.5 mL NS via SVN; mix with albuterol (DuoNeb)',
    pedsDose: '0.25-0.5 mg SVN mixed with albuterol',
    routes: ['Inhaled (SVN)', 'MDI'],
    onset: '5-15 min',
    duration: '3-6 hours',
    notes: 'Use only in first hour of treatment, then discontinue. Combined Albuterol/Ipratropium available as DuoNeb.',
    scope: 'Both',
  },
  {
    id: 'atropine',
    name: 'Atropine Sulfate',
    category: 'Cardiac',
    class: 'Anticholinergic / Parasympatholytic',
    indications: ['Symptomatic bradycardia (2nd/3rd degree AV block)', 'Organophosphate/nerve agent poisoning', 'Asystole (cardiac arrest)'],
    contraindications: ['Tachycardia', 'Acute angle-closure glaucoma', 'Obstructive uropathy'],
    sideEffects: ['Tachycardia', 'Dry mouth', 'Blurred vision', 'Urinary retention', 'Paradoxical bradycardia (< 0.5 mg)'],
    adultDose: 'Bradycardia: 0.5-1 mg IV/IO q3-5 min (max 3 mg) | Organophosphate: 2-4 mg IV q5-10 min until secretions dry',
    pedsDose: '0.02 mg/kg IV/IO (min 0.1 mg, max 0.5 mg per dose)',
    routes: ['IV', 'IO', 'IM', 'ET (2-3x IV dose)'],
    onset: 'IV: 1 min',
    duration: '4-6 hours',
    notes: 'Minimum dose 0.5 mg in adults (paradoxical bradycardia risk). For organophosphate OD, give large doses rapidly until secretions dry (can exceed normal limits).',
    scope: 'Both',
  },
  {
    id: 'dextrose',
    name: 'Dextrose (D50W / D10W)',
    category: 'Toxicology',
    class: 'Carbohydrate / Glucose Solution',
    indications: ['Hypoglycemia (BGL < 60-70 mg/dL with symptoms)', 'Altered mental status with confirmed hypoglycemia'],
    contraindications: ['Hyperglycemia', 'Intracranial hemorrhage without hypoglycemia (relative)', 'Thiamine deficiency without thiamine pretreatment'],
    sideEffects: ['Hyperglycemia', 'Phlebitis', 'Tissue necrosis if extravasation', 'Worsening neurological outcome in stroke (avoid if no hypoglycemia)'],
    adultDose: 'D50W: 25 g (50 mL) IV | If D50 unavailable: D10W 250 mL IV',
    pedsDose: 'D10W: 5 mL/kg IV | D25W: 2 mL/kg IV (max 25g)',
    routes: ['IV', 'IO'],
    onset: '1-3 min',
    duration: 'Variable',
    notes: 'Confirm hypoglycemia with glucometer before giving. D10 preferred in most systems due to lower osmolality. Give thiamine 100 mg IV before dextrose in known alcoholics.',
    scope: 'Both',
  },
  {
    id: 'glucagon',
    name: 'Glucagon',
    category: 'Toxicology',
    class: 'Pancreatic Hormone',
    indications: ['Hypoglycemia without IV access', 'Beta-blocker overdose (high dose)', 'Calcium channel blocker overdose'],
    contraindications: ['Pheochromocytoma', 'Insulinoma', 'Starvation (ineffective — no glycogen stores)'],
    sideEffects: ['Nausea', 'Vomiting', 'Tachycardia', 'Hyperglycemia'],
    adultDose: 'Hypoglycemia: 1 mg IM/SQ | Beta-blocker OD: 2-5 mg IV over 1 min, then 2-5 mg/hr infusion',
    pedsDose: '< 20 kg: 0.5 mg IM | > 20 kg: 1 mg IM',
    routes: ['IM', 'SQ', 'IV'],
    onset: 'IM: 8-10 min | IV: 1-2 min',
    duration: '45-90 min',
    notes: 'Less effective if patient is alcoholic, malnourished, or has been fasting (no glycogen stores). Position patient for potential vomiting.',
    scope: 'Both',
  },
  {
    id: 'ketamine',
    name: 'Ketamine',
    category: 'Airway/RSI',
    class: 'Dissociative Anesthetic / NMDA Antagonist',
    indications: ['Excited delirium / severe agitation', 'RSI induction', 'Procedural sedation', 'Refractory pain (analgesic dose)', 'Status asthmaticus refractory to bronchodilators'],
    contraindications: ['Uncontrolled hypertension', 'Known schizophrenia', 'Thyroid disease (relative)', 'Head trauma with elevated ICP (relative — no longer absolute CI in most systems)'],
    sideEffects: ['Emergence reactions (combativeness, hallucinations)', 'Hypersalivation', 'Laryngospasm', 'Transient increase in BP/HR/ICP', 'Tachycardia'],
    adultDose: 'Sedation/agitation: 4-5 mg/kg IM | RSI: 1-2 mg/kg IV | Analgesic: 0.1-0.3 mg/kg IV slow push',
    pedsDose: 'Sedation: 3-5 mg/kg IM | Analgesic: 0.5 mg/kg IV slow',
    routes: ['IV', 'IM', 'IO', 'IN'],
    onset: 'IV: 30-60 sec | IM: 3-5 min',
    duration: 'IV: 10-15 min | IM: 15-30 min',
    notes: 'Preferred agent for excited delirium. Maintains airway reflexes and bronchodilates. Have BVM and suction ready. Consider glycopyrrolate or atropine to reduce secretions.',
    scope: 'Paramedic',
  },
  {
    id: 'succinylcholine',
    name: 'Succinylcholine',
    genericName: 'Anectine',
    category: 'Airway/RSI',
    class: 'Depolarizing Neuromuscular Blocker',
    indications: ['RSI (rapid sequence intubation)', 'Emergency airway management'],
    contraindications: ['Burns > 72 hours', 'Crush injuries > 72 hours', 'Denervation injuries', 'Known hyperkalemia', 'Personal/family history of malignant hyperthermia', 'Penetrating eye injuries'],
    sideEffects: ['Fasciculations', 'Hyperkalemia (life-threatening in denervated muscle)', 'Malignant hyperthermia', 'Bradycardia', 'Increased ICP/IOP'],
    adultDose: '1.5 mg/kg IV (typical 100-150 mg)',
    pedsDose: '2 mg/kg IV (<10 kg); 1.5 mg/kg IV (>10 kg)',
    routes: ['IV', 'IO', 'IM (not preferred)'],
    onset: '45-60 sec',
    duration: '8-10 min',
    notes: 'Depolarizing NMB. Use within 48-72 hours of burns/crush injury. If contraindicated, use rocuronium (1.2 mg/kg) instead. Pretreat with atropine 0.01 mg/kg in children.',
    scope: 'Paramedic',
  },
  {
    id: 'diphenhydramine',
    name: 'Diphenhydramine',
    genericName: 'Benadryl',
    category: 'Pain/Sedation',
    class: 'H1 Antihistamine / Anticholinergic',
    indications: ['Anaphylaxis (adjunct to epinephrine)', 'Allergic reaction', 'Dystonic reaction (phenothiazine toxicity)', 'Nausea (adjunct)'],
    contraindications: ['Neonates', 'Narrow-angle glaucoma', 'Benign prostatic hyperplasia (relative)', 'MAO inhibitor use'],
    sideEffects: ['Sedation', 'Dry mouth', 'Urinary retention', 'Tachycardia', 'Paradoxical excitation in children'],
    adultDose: '25-50 mg IV/IM; PO 25-50 mg',
    pedsDose: '1 mg/kg IV/IM (max 50 mg per dose)',
    routes: ['IV', 'IM', 'PO'],
    onset: 'IV: 1-3 min | IM: 15-30 min',
    duration: '4-8 hours',
    notes: 'Second-line in anaphylaxis — epinephrine is always first. Useful for urticaria and allergic reactions. May cause significant sedation.',
    scope: 'Both',
  },
  {
    id: 'ondansetron',
    name: 'Ondansetron',
    genericName: 'Zofran',
    category: 'Pain/Sedation',
    class: 'Serotonin 5-HT3 Antagonist',
    indications: ['Nausea and vomiting', 'Post-medication nausea (opioid-induced)', 'Nausea in cardiac/stroke patients'],
    contraindications: ['Known hypersensitivity', 'Congenital long QT syndrome', 'Concurrent use of apomorphine'],
    sideEffects: ['Headache', 'QT prolongation (rare)', 'Constipation', 'Transient vision changes'],
    adultDose: '4 mg IV/IM slow push; may repeat once in 15-30 min (max 8 mg per dose)',
    pedsDose: '0.1 mg/kg IV/IM (max 4 mg)',
    routes: ['IV', 'IM', 'ODT (orally dissolving tablet)'],
    onset: 'IV: 1-3 min | IM: 15-30 min',
    duration: '4-8 hours',
    notes: 'Preferred antiemetic in EMS. Safe with opioids. Dissolving tablet (ODT) useful when IV unavailable.',
    scope: 'Both',
  },
  {
    id: 'sodium-bicarb',
    name: 'Sodium Bicarbonate',
    genericName: 'NaHCO3',
    category: 'Toxicology',
    class: 'Alkalinizing Agent / Buffer',
    indications: ['Cardiac arrest with hyperkalemia or TCA overdose', 'Tricyclic antidepressant toxicity (QRS > 100ms)', 'Metabolic acidosis', 'Hyperkalemia'],
    contraindications: ['Metabolic/respiratory alkalosis', 'Pulmonary edema (relative)', 'CHF (relative)'],
    sideEffects: ['Metabolic alkalosis', 'Hypocalcemia', 'Hypokalemia', 'Paradoxical intracellular acidosis', 'Tissue necrosis if extravasation'],
    adultDose: '1 mEq/kg IV/IO bolus; may repeat 0.5 mEq/kg q10 min',
    pedsDose: '1 mEq/kg IV/IO slow push (dilute 1:1 with sterile water in neonates)',
    routes: ['IV', 'IO'],
    onset: '< 1 min',
    duration: '1-2 hours',
    notes: 'Use 8.4% solution (1 mEq/mL). Do not mix with calcium. Flush line between medications. Use in TCA overdose even if no acidosis.',
    scope: 'Paramedic',
  },
  {
    id: 'calcium-chloride',
    name: 'Calcium Chloride',
    category: 'Cardiac',
    class: 'Electrolyte',
    indications: ['Hyperkalemia (with ECG changes)', 'Calcium channel blocker overdose', 'Hypocalcemia', 'Hydrofluoric acid exposure', 'Magnesium toxicity'],
    contraindications: ['Digoxin toxicity (relative)', 'Hypercalcemia', 'Ventricular fibrillation'],
    sideEffects: ['Bradycardia', 'Hypotension (rapid infusion)', 'Tissue necrosis (extravasation)', 'Nausea', 'Hypercalcemia'],
    adultDose: '1 g (10 mL of 10% solution) IV slow push over 5-10 min; may repeat in 10 min',
    pedsDose: '20 mg/kg IV slow push (max 1 g)',
    routes: ['IV (central preferred; peripheral OK in emergency)', 'IO'],
    onset: '1-3 min',
    duration: '30-60 min',
    notes: 'Do NOT mix with sodium bicarbonate. Precipitates. Preferred over calcium gluconate in emergency. More concentrated than gluconate.',
    scope: 'Paramedic',
  },
  {
    id: 'magnesium-sulfate',
    name: 'Magnesium Sulfate',
    category: 'Seizure/Neuro',
    class: 'Electrolyte / Antidysrhythmic',
    indications: ['Torsades de pointes', 'Eclampsia/pre-eclampsia seizures', 'Severe asthma refractory to bronchodilators', 'Hypomagnesemia'],
    contraindications: ['Hypermagnesemia', 'Renal failure', 'Heart block (relative)'],
    sideEffects: ['Respiratory depression (toxicity)', 'Hypotension', 'Loss of DTRs (first sign of toxicity)', 'Cardiac arrest (severe overdose)', 'Flushing'],
    adultDose: 'Torsades: 1-2 g IV over 5-20 min | Eclampsia: 4-6 g IV over 15-20 min | Asthma: 2 g IV over 20 min',
    pedsDose: '25-50 mg/kg IV (max 2 g per dose)',
    routes: ['IV', 'IO', 'IM (painful)'],
    onset: 'IV: 1-5 min',
    duration: '30 min',
    notes: 'Calcium chloride is antidote for mag toxicity. Monitor DTRs, respiratory rate, urine output. Stop if respirations < 12/min or DTRs absent.',
    scope: 'Paramedic',
  },
  {
    id: 'tranexamic-acid',
    name: 'Tranexamic Acid',
    genericName: 'TXA',
    category: 'Toxicology',
    class: 'Antifibrinolytic',
    indications: ['Traumatic hemorrhage within 3 hours of injury', 'Significant bleeding in trauma patients', 'Post-partum hemorrhage'],
    contraindications: ['Time > 3 hours post-injury (may be harmful)', 'History of thromboembolic disease (relative)', 'Subarachnoid hemorrhage (relative)'],
    sideEffects: ['Nausea/vomiting (rapid infusion)', 'Hypotension (rapid infusion)', 'Thromboembolic events', 'Seizures (very high doses)'],
    adultDose: '1 g IV over 10 min (slow push over 10 min is acceptable); administer within 3 hours of injury',
    pedsDose: '15 mg/kg IV over 10 min (max 1 g)',
    routes: ['IV', 'IO'],
    onset: 'Immediate',
    duration: '3 hours',
    notes: 'Effective only within 3 hours of injury — document time of injury. Administer slowly to avoid hypotension. Part of hemorrhagic shock protocol.',
    scope: 'Paramedic',
  },
  {
    id: 'norepinephrine',
    name: 'Norepinephrine',
    genericName: 'Levophed',
    category: 'Cardiac',
    class: 'Catecholamine / Alpha-1 Agonist',
    indications: ['Septic shock', 'Neurogenic shock', 'Distributive shock refractory to fluid resuscitation'],
    contraindications: ['Hypovolemic shock without fluid resuscitation', 'Peripheral vascular disease (relative)'],
    sideEffects: ['Hypertension', 'Reflex bradycardia', 'Tissue ischemia/necrosis (extravasation)', 'Dysrhythmias'],
    adultDose: '0.01-3 mcg/kg/min IV infusion; titrate to MAP > 65 mmHg',
    pedsDose: '0.1-2 mcg/kg/min IV infusion',
    routes: ['IV infusion (central line preferred)', 'IO (short-term)'],
    onset: '1-2 min',
    duration: '1-2 min after stopping infusion',
    notes: 'First-line vasopressor for septic shock. Use large-bore proximal IV or IO in pre-hospital. Tissue necrosis risk with extravasation — use central access when possible.',
    scope: 'Paramedic',
  },
];

export const drugCategories = [
  'All',
  'Cardiac',
  'Airway/RSI',
  'Pain/Sedation',
  'Seizure/Neuro',
  'Toxicology',
];
