import { WeightDrug } from '../types/drug';

export const weightDrugs: WeightDrug[] = [
  {
    id: 'epi-cardiac',
    name: 'Epinephrine (Cardiac Arrest)',
    indication: 'VF/VT/PEA/Asystole',
    dosePerKg: 0.01,
    unit: 'mg',
    maxDose: 1,
    route: 'IV/IO',
    concentration: '1:10,000 (0.1 mg/mL)',
    notes: 'Repeat every 3-5 minutes during cardiac arrest',
    scope: 'Both',
    pediatricMaxDose: 1,
    pediatricNote: 'Peds max: 1 mg/dose IV/IO. Same weight-based dose (0.01 mg/kg); no dose reduction.',
  },
  {
    id: 'epi-anaphylaxis',
    name: 'Epinephrine (Anaphylaxis)',
    indication: 'Anaphylaxis / Severe Allergic Reaction',
    dosePerKg: 0.01,
    unit: 'mg',
    maxDose: 0.5,
    route: 'IM (lateral thigh)',
    concentration: '1:1,000 (1 mg/mL)',
    notes: 'Use EpiPen 0.3mg (adult) or 0.15mg (peds < 30 kg)',
    scope: 'Both',
    pediatricMaxDose: 0.3,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 0.3 mg IM. Use EpiPen Jr 0.15 mg if < 30 kg.',
  },
  {
    id: 'amiodarone-cardiac',
    name: 'Amiodarone (Cardiac Arrest)',
    indication: 'Refractory VF/Pulseless VT',
    dosePerKg: 5,
    unit: 'mg',
    maxDose: 300,
    route: 'IV/IO bolus',
    concentration: '50 mg/mL',
    notes: 'First dose. Second dose: 2.5 mg/kg (max 150 mg)',
    scope: 'Paramedic',
    pediatricMaxDose: 300,
    pediatricNote: 'Peds max: 300 mg/dose IV/IO. 5 mg/kg same dose; do not exceed adult max.',
  },
  {
    id: 'adenosine',
    name: 'Adenosine (1st dose)',
    indication: 'SVT / PSVT',
    dosePerKg: 0.1,
    unit: 'mg',
    maxDose: 6,
    route: 'Rapid IV push + flush',
    concentration: '3 mg/mL',
    notes: '2nd dose: 0.2 mg/kg (max 12 mg). Rapid push is essential.',
    scope: 'Paramedic',
    pediatricMaxDose: 6,
    pediatricNote: 'Peds max: 6 mg 1st dose, 12 mg 2nd dose. Same weight-based dosing.',
  },
  {
    id: 'atropine-brady',
    name: 'Atropine (Bradycardia)',
    indication: 'Symptomatic Bradycardia',
    dosePerKg: 0.02,
    unit: 'mg',
    maxDose: 0.5,
    maxDoseUnit: 'mg per dose (min 0.1 mg)',
    route: 'IV/IO',
    concentration: '0.1 mg/mL or 1 mg/mL',
    notes: 'Min 0.1 mg, max 0.5 mg per dose. May repeat; total max 3 mg in adults.',
    scope: 'Both',
    pediatricMaxDose: 0.5,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 0.5 mg/dose; minimum 0.1 mg to avoid paradoxical bradycardia. Total peds max: 1 mg.',
  },
  {
    id: 'fentanyl',
    name: 'Fentanyl (Analgesia)',
    indication: 'Moderate to Severe Pain',
    dosePerKg: 1,
    unit: 'mcg',
    maxDose: 100,
    route: 'IV/IO slow push or IN',
    concentration: '50 mcg/mL',
    notes: 'Titrate to effect. Intranasal: 2 mcg/kg via MAD (max 100 mcg per nare)',
    scope: 'Paramedic',
    pediatricMaxDose: 50,
    pediatricMaxDoseUnit: 'mcg',
    pediatricNote: 'Peds max: 50 mcg/dose IV/IO. Reduce to 1 mcg/kg; max single dose 50 mcg per CAZRB.',
  },
  {
    id: 'morphine',
    name: 'Morphine Sulfate',
    indication: 'Pain Management',
    dosePerKg: 0.1,
    unit: 'mg',
    maxDose: 5,
    route: 'IV slow push',
    concentration: '10 mg/mL',
    notes: 'Titrate in 2-4 mg increments. Monitor respirations and BP.',
    scope: 'Paramedic',
    pediatricMaxDose: 2,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 2 mg/dose. Use with caution; fentanyl preferred in pediatric patients.',
  },
  {
    id: 'midazolam-sz',
    name: 'Midazolam (Seizure)',
    indication: 'Active Seizure / Status Epilepticus',
    dosePerKg: 0.2,
    unit: 'mg',
    maxDose: 10,
    route: 'IM or IN',
    concentration: '5 mg/mL',
    notes: 'IM preferred if no IV. Intranasal: use atomizer (MAD). May repeat half dose once.',
    scope: 'Paramedic',
    pediatricMaxDose: 5,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 5 mg/dose IM/IN. 0.2 mg/kg same; do not exceed 5 mg per CAZRB.',
  },
  {
    id: 'naloxone-iv',
    name: 'Naloxone (Opioid OD)',
    indication: 'Opioid Overdose / Respiratory Depression',
    dosePerKg: 0.01,
    unit: 'mg',
    maxDose: 0.4,
    route: 'IV/IO/IM/IN',
    concentration: '0.4 mg/mL or 1 mg/mL',
    notes: 'Titrate to adequate breathing — not full reversal. Duration 30-90 min, shorter than most opioids.',
    scope: 'Both',
    pediatricMaxDose: 0.1,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 0.1 mg/dose. Titrate carefully; smaller doses reduce risk of acute withdrawal.',
  },
  {
    id: 'dextrose-d10',
    name: 'Dextrose (D10W)',
    indication: 'Hypoglycemia',
    dosePerKg: 5,
    unit: 'mL',
    maxDose: 250,
    maxDoseUnit: 'mL',
    route: 'IV/IO',
    concentration: 'D10W (10% dextrose)',
    notes: 'Confirm hypoglycemia with glucometer before giving. Recheck BGL after 5-10 min.',
    scope: 'Both',
    pediatricMaxDose: 100,
    pediatricMaxDoseUnit: 'mL',
    pediatricNote: 'Peds max: 5 mL/kg D10W (max 100 mL). Preferred over D50 in pediatric patients.',
  },
  {
    id: 'ketamine-agitation',
    name: 'Ketamine (Agitation)',
    indication: 'Excited Delirium / Severe Agitation',
    dosePerKg: 4,
    unit: 'mg',
    maxDose: 500,
    route: 'IM',
    concentration: '500 mg/10 mL (50 mg/mL)',
    notes: 'Use 5 mg/kg IM for faster onset in severe cases. Draw up carefully due to concentration.',
    scope: 'Paramedic',
    pediatricMaxDose: 300,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 300 mg IM. Rarely indicated < 15 yr; consult medical direction.',
  },
  {
    id: 'ketamine-rsi',
    name: 'Ketamine (RSI)',
    indication: 'Rapid Sequence Intubation — Induction',
    dosePerKg: 1.5,
    unit: 'mg',
    maxDose: 200,
    route: 'IV slow push',
    concentration: '500 mg/10 mL (50 mg/mL)',
    notes: 'Follow with succinylcholine 1.5 mg/kg or rocuronium 1.2 mg/kg. Administer over 30-60 seconds.',
    scope: 'Paramedic',
    pediatricMaxDose: 150,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 150 mg IV. 1.5 mg/kg dose same; monitor for laryngospasm.',
  },
  {
    id: 'succinylcholine',
    name: 'Succinylcholine (RSI)',
    indication: 'Neuromuscular Blockade for Intubation',
    dosePerKg: 1.5,
    unit: 'mg',
    maxDose: 200,
    route: 'IV/IO',
    concentration: '20 mg/mL',
    notes: 'Onset 45-60 sec. Duration 8-10 min. Check for contraindications before use.',
    scope: 'Paramedic',
    pediatricMaxDose: 150,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds: use 2 mg/kg for infants < 10 kg. Max 150 mg. Avoid in hyperkalemia risk.',
  },
  {
    id: 'diphenhydramine',
    name: 'Diphenhydramine (Benadryl)',
    indication: 'Allergic Reaction / Anaphylaxis Adjunct',
    dosePerKg: 1,
    unit: 'mg',
    maxDose: 50,
    route: 'IV/IM',
    concentration: '50 mg/mL',
    notes: 'Second-line to epinephrine in anaphylaxis. Used for urticaria and allergic reactions.',
    scope: 'Both',
    pediatricMaxDose: 25,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 25 mg/dose IV/IM. Do not exceed 1 mg/kg or 25 mg per CAZRB.',
  },
  {
    id: 'albuterol',
    name: 'Albuterol (SVN)',
    indication: 'Bronchospasm / Asthma',
    dosePerKg: 0,
    unit: 'mg',
    maxDose: 2.5,
    route: 'Inhaled via SVN',
    concentration: '0.083% (2.5 mg/3 mL)',
    notes: 'Fixed dosing: 2.5 mg adult / 1.25 mg peds (<20 kg). Not weight-based. May repeat every 20 min x3.',
    scope: 'Both',
    pediatricOnly: false,
    pediatricMaxDose: 1.25,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds dose: 1.25 mg SVN (< 20 kg). Fixed dose — not weight-based.',
  },
  {
    id: 'calcium-chloride',
    name: 'Calcium Chloride',
    indication: 'Hyperkalemia / CCB Overdose',
    dosePerKg: 20,
    unit: 'mg',
    maxDose: 1000,
    route: 'IV slow push over 5-10 min',
    concentration: '10% (100 mg/mL)',
    notes: 'Do NOT mix with sodium bicarbonate. Slow administration to avoid bradycardia.',
    scope: 'Paramedic',
    pediatricMaxDose: 500,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 20 mg/kg (max 500 mg). Administer slowly over 10 min; monitor for bradycardia.',
  },
  {
    id: 'ondansetron',
    name: 'Ondansetron (Zofran)',
    indication: 'Nausea / Vomiting',
    dosePerKg: 0.1,
    unit: 'mg',
    maxDose: 4,
    route: 'IV/IM or ODT',
    concentration: '2 mg/mL',
    notes: 'May repeat once in 15 min. ODT (orally dissolving tablet) if no IV access.',
    scope: 'Both',
    pediatricMaxDose: 4,
    pediatricMaxDoseUnit: 'mg',
    pediatricNote: 'Peds max: 4 mg/dose. Not recommended under 2 years without medical direction.',
  },
];
